### ISSUE TITLE
Needs to be updated to work with Active911's new API

### ISSUE THREAD

**Issue by benburwell** [benburwell/active911#1]
Here is the spec: http://wiki.active911.com/wiki/index.php/Accessing_the_API

**Comment by iHwy** [comment]
Ben, Any movement on this?

**Comment by benburwell** [comment]
Haven't had the chance to do this yet unfortunately. However I am working on a project that I'll probably need this for soon. PRs definitely welcome in the meantime :)

**Comment by benburwell** [comment]
Hey iHwy, I'm actively working on this now -- see the `develop` branch. I expect to have a functional version with the new API up on npm by next weekend. If this is something you're interested in using, please have a look at the code and let me know if you have any comments. Thanks!

**Comment by iHwy** [comment]
Great. I will definitely have a look.

**Comment by benburwell** [comment]
Active911@1.0.0 is now [available on npm](https://www.npmjs.com/package/active911)
